Develop
Artemev1986/java-explore-with-me pull request #1
Opened 2022-10-27 13:04 UTC by Artemev1986

2022-10-28 20:06 UTC, EvgenyKoptubenko commented on README.md
> +
Документация это всегда круто. На английском круто вдвойне. Спасибо огромное

2022-10-28 20:08 UTC, EvgenyKoptubenko commented on ewm/src/main/java/ru/yandex/practicum/ewm/controller/AdminCategoryController.java
> +package ru.yandex.practicum.ewm.controller;
все контроллеры в одном пакете. Oh stop that you. Спасибо огромное

2022-10-28 20:10 UTC, EvgenyKoptubenko commented on ewm/src/main/java/ru/yandex/practicum/ewm/controller/ErrorHandler.java
> +  @ExceptionHandler(value = {MethodArgumentNotValidException.class, ValidationException.class})
Нет дублирования и эксепшены через запятую перечислены. Круто.

2022-10-28 20:12 UTC, EvgenyKoptubenko commented on ewm/src/main/resources/messages.properties
> +name.notblank=name must not be blank.
Сообщения в отдельном файле и можно будет потом сделать интернационализацию сообщений. Ой май гадбл

2022-10-28 20:14 UTC, EvgenyKoptubenko commented on ewm/src/main/java/ru/yandex/practicum/ewm/model/Category.java
> +    public boolean equals(Object o) {
У всех классов модели одна и та же функция hashCode и equals, может быть их вынести в отдельный класс и всем пронаследоваться от него?

2022-10-28 20:15 UTC, EvgenyKoptubenko commented on ewm/src/main/java/ru/yandex/practicum/ewm/repository/EventRepository.java
> +    @Query("SELECT ev FROM Event ev WHERE " +
Что ты делаешь... переменные не из одной буквы. Круто. спасибо

2022-10-28 20:17 UTC, EvgenyKoptubenko commented on ewm/pom.xml
> +    <dependencies>
Нет миллиона зависимостей - круто

2022-10-28 20:20 UTC, EvgenyKoptubenko requested changes
Считаю проект практически идеальным. У меня только одно предложение и то не особо существенно

2022-10-30 15:45 UTC, Artemev1986 commented on ewm/src/main/java/ru/yandex/practicum/ewm/model/Category.java
> +    public boolean equals(Object o) {
Сделал. Спасибо

2022-10-30 15:49 UTC, Artemev1986 commented
Сделал рефакторинг классов моделей, используя стратегию MappedSuperclass. Перенес в базовую сущность переопределение методов hashCode и equals.

2022-10-30 20:24 UTC, EvgenyKoptubenko approved these changes
На текущий момент реализация этого проекта на первом месте в моей рейтинге. Сделано очень хорошо. Спасибо огромное.

На будущее, например, когда будут спрашивать на собеседовании, то в проекте еще должно быть:
* 		Healthcheck (отдельный эндпоинт, который возвращает данные о том как себя чувствует приложение) - например описать как работает Spring Actuator
* 		На основе Healthcheck можно делать мониторинг, который будет периодически дергать этот эндпоинт и если что-то в healthcheck сломалось, то присылает алерты
* 		Так же в проекте должна быть документация, которая автоматически собирается - Docsify, например
* 		Так что должно быть отдельное приложение, которое собирает проект, создает артифакт и складывает его в хранилище. В Github тоже можно такое сделать.
* 		Во время код ревью должен подключаться Sonar для проверок.
* 		Во время пул реквеста так же должно подсчитываться покрытие кода тестами
* 		Приложение должно быть защищено, т.е. неавторизованные пользователи не должны иметь доступ к эндпоинтам. Почитай про OAUTH2
* 		В пул реквестах должно быть настроено минимальное количество апруверов, которые должны проверить и заапрувить пул реквест перед тем как его можно мерджить
* 		Все должно быть покрыто юнит тестами, так же должны быть написаны BDD тесты.
* 		Все, что не дает коду пройти в прод называется Quality Gates. К таким quality gates можно причислить: jUnit tests, BDD tests, Sonar, Pull Requests checks, code coverage, Catchpoint tests, Performance tests, Browserstack tests.
* 		Так же в приложении должен быть код, который создает инфраструктуру. Например, если ты хостишься в Amazon, то через Terraform нужно создать инфру.
* 		Дополнительный мониториг бизнес фич. У тебя должны быть графики о том как дела у приложения и у клиентов. И так же настроены алерты, если что-то пошло не так.

2022-10-30 21:28 UTC, merged